export interface EnqueueParams {
  /** Caller-supplied message ID. If omitted, one is generated by the queue. */
  id?: string
  to: string
  body: string
  idempotencyKey: string
  priority?: number
  senderNumber?: string
  pluginName?: string
  correlationId?: string
  sendersConfig?: string
  context?: string
  maxRetries?: number
  mediaUrl?: string
  mediaType?: string
  mediaCaption?: string
  contactName?: string
}

export interface Message {
  id: string
  to: string
  body: string
  idempotencyKey: string
  priority: number
  senderNumber: string | null
  status: MessageStatus
  attempts: number
  lockedBy: string | null
  lockedAt: string | null
  createdAt: string
  updatedAt: string
  pluginName: string | null
  correlationId: string | null
  sendersConfig: string | null
  context: string | null
  wahaMessageId: string | null
  maxRetries: number
  sentAt: string | null
  fallbackUsed: number
  fallbackProvider: string | null
  screenshotPath: string | null
  screenshotStatus: string | null
  screenshotSkipReason: string | null
  screenshotDeletedAt: string | null
  screenshotSizeBytes: number | null
  mediaUrl: string | null
  mediaType: string | null
  mediaCaption: string | null
}

export type MessageStatus =
  | 'queued'
  | 'locked'
  | 'sending'
  | 'sent'
  | 'failed'
  | 'permanently_failed'
  | 'waiting_device'

export const VALID_TRANSITIONS: Record<MessageStatus, MessageStatus[]> = {
  queued: ['locked', 'waiting_device', 'permanently_failed'],
  locked: ['sending', 'queued', 'permanently_failed'],
  sending: ['sent', 'failed', 'queued', 'permanently_failed'],
  sent: [],
  failed: ['queued', 'permanently_failed'],
  permanently_failed: ['queued'],
  waiting_device: ['queued', 'permanently_failed'],
}

export interface SkippedItem {
  idempotencyKey: string
  reason: 'blacklisted' | 'duplicate'
  to?: string
}

export interface BatchResult {
  enqueued: Message[]
  skipped: SkippedItem[]
}

export interface PaginatedFilters {
  limit?: number
  offset?: number
  status?: string
  pluginName?: string
  phone?: string
  senderNumber?: string
  dateFrom?: string
  dateTo?: string
}

export interface PaginatedResult {
  data: Message[]
  total: number
}
